name: Sync Aliyun to Docker Hub
on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Aliyun ACR
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_CREDENTIAL.split(':')[0] }}
          password: ${{ secrets.ALIYUN_CREDENTIAL.split(':')[1] }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Sync Image via Skopeo
        run: |
          skopeo copy \
            docker://registry.cn-hangzhou.aliyuncs.com/your-namespace/image:tag \
            docker://docker.io/your-dockerhub-username/image:tag
